### ISSUE TITLE
Project installation instructions may require a refresh.

### ISSUE THREAD

**Issue by jmichaelward** [joindin/joindin-vm#94]
I attempted to stand up the project locally on macOS 10.14.3 following the step-by-step instructions defined in the README. Everything seemed to be working well - Git correctly pulled in my forks of the submodules, Vagrant provisioned, and Composer installed packages by way of the handy installer script described in Step 4. Once I got to Step 8, however, the app was not rendering as expected:

- dev.joind.in rendered a 404 notice: ![Screenshot](https://www.dropbox.com/s/i4unqji3cfzujwk/Screenshot%202019-02-23%2011.57.09.png?raw=1)
- legacy.dev.joind.in rendered a standard Apache "It Works!" message: ![Screenshot](https://www.dropbox.com/s/d08oezpfd5lhi2o/Screenshot%202019-02-23%2011.58.12.png?raw=1)
- api.dev.joind.in rendered the various routes correctly, but clicking into any of them displayed an SQLSTATE message indicating that the user table does not have a biography field:
![Screenshot](https://www.dropbox.com/s/07bbg931mpdr64l/Screenshot%202019-02-23%2011.58.59.png?raw=1)
![Screenshot](https://www.dropbox.com/s/u2szwzo7u99v9hn/Screenshot%202019-02-23%2011.59.16.png?raw=1)

It's not clear whether I missed a step in the install process, or whether the README requires some updates to coincide with changes to the repository. 

Version notes, just in case anything here is useful:
- VirtualBox 6.0.4 r128413
- Vagrant 2.2.3
- Composer 1.8.0
- PHP 7.2.15

**Comment by ericpoe** [comment]
@jmichaelward I am unable to recreate the problem locally with a fresh fork.

* OSX 10.14.3
* VirtualBox 6.0.4 r128413
* Vagrant 2.2.3
* Composer 1.8.4

Which Vagrant plugins are you using? `vagrant plugin list` on my end shows:

* vagrant-hostsupdater (1.1.1.16, global)
* vagrant-vbguest (0.17.2, global)

If you are missing any of those plugins, please install via `vagrant plugin install vagrant-name-of-plugin` and then run `vagrant up --provision` to reprovision your vagrant box with the new new plugins. Please let me know how that works for you.

**Comment by jmichaelward** [comment]
@ericpoe Thanks for looking into this so quickly. I ran `vagrant plugin list`, which showed only the `hostsupdater` plugin installed. After installing the `vbguest` plugin and re-provisioning the box, but the `dev` and `api` sites appear to be working correctly (Legacy is still showing a default Apache success page, but I'm less concerned with that in order to contribute to the project going forward).

As I see it, there are two opportunities for updating the documentation:

1. Consider updating Step 7 to recommend installing the Hostsupdater plugin. It's not required in order to correctly resolve DNS locally (since the step of manually updating one's hosts file is an option), but adding a statement to optionally run `vagrant plugin install vagrant-hostsupdater` and then `vagrant up --provision` during step 7 might alleviate some headaches for future newcomers to the project.
2. Adding in that audit step about which Vagrant plugins are required. I'm an unusual case, perhaps, because I recently did a clean install of macOS and had deleted my Vagrant/VirtualBox instances before checking in on the progress for this project, and it appears that `vbguest` plugin is required. We should indicate it as such.

If we can confirm that at least the `vbguest` plugin is required, adding in number 2 from the list above should help resolve future issues.

**Comment by ericpoe** [comment]
@jmichaelward can you pull from upstream master again and let me know how these instructions work for you?

**Comment by jmichaelward** [comment]
@ericpoe 10-4. I'll schedule myself some time to give it a look tomorrow morning and we'll get back to you with feedback. Thanks.

**Comment by jmichaelward** [comment]
Hey @ericpoe, I apologize for the late response on this. I went through the instructions again this morning, first pulling the master updates into my vm, api, and web2 repositories, then going through the step-by-step instructions from scratch. 

Upon trying to perform the `php ./vendor/bin/homestead make` command after running `php scripts/cloneRepository.php`, I'm greeted with a message that homestead doesn't exist, because the joindin-vm repository never gets `composer install` run on it. After running `composer install`, I'm able to run the Homestead command, but when trying to run `vagrant up`, it fails out with the following message:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
```

I wouldn't be certain that this is related to the install process itself, as I've been having intermittent issues with my machine of late, but I can confirm that I'm running the latest of both VirtualBox (6.0.4 r128413) and Vagrant (2.2.4).

In reviewing the remaining steps, I know I will no longer be affected by the `hostsupdater` installation since it exists from my previous install, but I do think that step should come before the step to run `vagrant up`. Otherwise, from what I can tell, the rest of the instructions seem clear.

**Comment by jmichaelward** [comment]
Update: I searched that error and found this on StackOverflow (https://stackoverflow.com/questions/21069908/vboxmanage-error-failed-to-create-the-host-only-adapter), which resolved the VirtualBox issue. Going through the rest of the installation instructions, the box provisioned and I was able to successfully access the expected URLs.

**Comment by ericpoe** [comment]
Thank you for testing this out @jmichaelward !
