### ISSUE TITLE
Find a way to provide latest vagrant box for hackathons & other limited wifi-events

### ISSUE THREAD

**Issue by ericpoe** [joindin/joindin-vm#96]
Once we are using Homestead for our Vagrant environment, we'll need a way to provide a latest build of the customized Homestead environment.

See: #95

**Comment by svpernova09** [comment]
## Sneakernet Laravel Homestead Instructions

Requirements:
* Source: The base box files of laravel/homestead. 
* Destination systems must use same provider as source

Copy the folder `~/vagrant.d/boxes/laravel-VAGRANTSLASH-homestead` to a drive to share. Copy this folder to `~/vagrant.d/boxes/lanhomestead` on the destination system. Once the copy is complete on the destination system you should be able to run `vagrant box list` and you should see an entry for "lanhomestead".

The next step is to disable the Homestead (repository) version check. Open ` scripts/homestead.rb` and locate a line that looks similar to ` config.vm.box_version = settings['version'] ||= '>= 1.0.0'` (the version number may be different), comment this line out by adding `# ` in front of it and save the file.

Now add the following line to `Homestead.yaml`: `box: lanstead`. Now you're ready to `vagrant up` from the same folder containing `Homestead.yaml`
